//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.bill_detail = new HashSet<bill_detail>();
        }
    
        public int id_bill { get; set; }
        public Nullable<double> total { get; set; }
        public string payment { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public string status { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<decimal> SDTKH { get; set; }
        public string DiaChiKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail> bill_detail { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
