//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.bill_detail = new HashSet<bill_detail>();
        }
    
        public int id_product { get; set; }
        public string name_product { get; set; }
        public string description { get; set; }
        public Nullable<int> unit_price { get; set; }
        public Nullable<int> promotion_price { get; set; }
        public string image { get; set; }
        public string unit { get; set; }
        public Nullable<int> id_type_product { get; set; }
        public Nullable<int> best { get; set; }
    
        public virtual type_product type_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail> bill_detail { get; set; }
    }
}
