//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slideshow
    {
        public int id_slideshow { get; set; }
        public string ImagePath { get; set; }
        public string Link { get; set; }
        public string Status { get; set; }
    }
}
